[phases.setup]
nixPkgs = ["...", "python3", "ffmpeg"]

[phases.build]
cmds = [
  "npm run build",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp",
  "chmod a+rx yt-dlp"
]
